### ISSUE TITLE
项目中缺少targetver.h和resource.h

### ISSUE THREAD

**Issue by bigQY** [Coral-Studio/Red-Spider-Hacker#1]

**Comment by HanHan666666** [comment]
我也是

**Comment by SkyNet-PKN** [comment]
你好，该项目已无限期停止维护，如仅需使用软件功能，只需要Release文件夹中的文件即可

**Comment by SkyNet-PKN** [comment]
您好，由于我们已经对该项目停止维护，未能及时处理消息，抱歉
我们已收到您的反馈，并作出更改，之前可能由于网络问题导致这两份文件上传失败，目前已经添加缺失的targetver.h和resource.h文件 @bigQY @HanHan666666
